### PR TITLE
added show-verbose-ver and app-attach examples

### PR DESCRIPTION
**Pull request by harshgondaliya**
Hi @edwarnicke

I have submitted a PR show implementing the `show-verbose-ver` and `app-attach` exercises.
Please check it out.

The following are outputs obtained for the respective applications:

**show-verbose-ver**
```
INFO[0000] VPP Version: 20.09-release
Compile Date: 2020-10-01T02:56:55
Compile Location: /w/workspace/vpp-merge-2009-ubuntu2004-x86_64 

```
**app-attach**
```
INFO[0000] Session Enabled                              
INFO[0000] Application Attached                         
INFO[0000] App Msg Queue: 28710464837910528
VPP Control Msg Queue: 4635329916504637440
VPP Control Queue Msg Thread Index: 0
App Index: 1
No. of fds exchanged: 2
FD Flags: 3
Segment Size: 4096
Segment Handle: 4294967296 
```

### CODE REVIEW

**Comment by edwarnicke** [comment]
This looks great so far!  Now lets add some CI to this PR:

https://github.com/godirect/hoststack/issues/4

**Comment by harshgondaliya** [comment]
@edwarnicke  

I have updated PR showing my work so far
Mainly I am confused about how to write the "docker" job and the "build" job 

Please let me know what all changes are needed.

**Comment by harshgondaliya** [comment]
@edwarnicke 

I have added CI support as you suggested.
I am using app-attach example for `docker build` and `go build`
Please check whether any changes are needed

**Comment by harshgondaliya** [comment]
@edwarnicke 

I have made all the changes that were needed to resolve CI failures.

Updated PR. Please have a look at it.

**Pull request merged**
